/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) model_2021_02_24_09504410_cost_y_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s1[23] = {19, 1, 0, 19, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[35] = {31, 1, 0, 31, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30};
static const casadi_int casadi_s4[65] = {27, 31, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 23, 24, 25, 26, 19, 20, 21, 22, 19, 20, 21, 22};

/* model_2021_02_24_09504410_cost_y_fun_jac_ut_xt:(i0[8],i1[19],i2[])->(o0[31],o1[27x31,31nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1]? arg[1][4] : 0;
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[1]? arg[1][8] : 0;
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[1]? arg[1][9] : 0;
  if (res[0]!=0) res[0][9]=a0;
  a0=arg[1]? arg[1][10] : 0;
  if (res[0]!=0) res[0][10]=a0;
  a0=arg[1]? arg[1][11] : 0;
  if (res[0]!=0) res[0][11]=a0;
  a0=arg[1]? arg[1][12] : 0;
  if (res[0]!=0) res[0][12]=a0;
  a0=arg[1]? arg[1][13] : 0;
  if (res[0]!=0) res[0][13]=a0;
  a0=arg[1]? arg[1][14] : 0;
  if (res[0]!=0) res[0][14]=a0;
  a0=arg[1]? arg[1][15] : 0;
  if (res[0]!=0) res[0][15]=a0;
  a0=arg[1]? arg[1][16] : 0;
  if (res[0]!=0) res[0][16]=a0;
  a0=arg[1]? arg[1][17] : 0;
  if (res[0]!=0) res[0][17]=a0;
  a0=arg[1]? arg[1][18] : 0;
  if (res[0]!=0) res[0][18]=a0;
  a0=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][19]=a0;
  a0=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][20]=a0;
  a0=arg[0]? arg[0][6] : 0;
  if (res[0]!=0) res[0][21]=a0;
  a0=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][22]=a0;
  a0=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][23]=a0;
  a1=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][24]=a1;
  a2=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][25]=a2;
  a3=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][26]=a3;
  if (res[0]!=0) res[0][27]=a0;
  if (res[0]!=0) res[0][28]=a1;
  if (res[0]!=0) res[0][29]=a2;
  if (res[0]!=0) res[0][30]=a3;
  a3=1.;
  if (res[1]!=0) res[1][0]=a3;
  if (res[1]!=0) res[1][1]=a3;
  if (res[1]!=0) res[1][2]=a3;
  if (res[1]!=0) res[1][3]=a3;
  if (res[1]!=0) res[1][4]=a3;
  if (res[1]!=0) res[1][5]=a3;
  if (res[1]!=0) res[1][6]=a3;
  if (res[1]!=0) res[1][7]=a3;
  if (res[1]!=0) res[1][8]=a3;
  if (res[1]!=0) res[1][9]=a3;
  if (res[1]!=0) res[1][10]=a3;
  if (res[1]!=0) res[1][11]=a3;
  if (res[1]!=0) res[1][12]=a3;
  if (res[1]!=0) res[1][13]=a3;
  if (res[1]!=0) res[1][14]=a3;
  if (res[1]!=0) res[1][15]=a3;
  if (res[1]!=0) res[1][16]=a3;
  if (res[1]!=0) res[1][17]=a3;
  if (res[1]!=0) res[1][18]=a3;
  if (res[1]!=0) res[1][19]=a3;
  if (res[1]!=0) res[1][20]=a3;
  if (res[1]!=0) res[1][21]=a3;
  if (res[1]!=0) res[1][22]=a3;
  if (res[1]!=0) res[1][23]=a3;
  if (res[1]!=0) res[1][24]=a3;
  if (res[1]!=0) res[1][25]=a3;
  if (res[1]!=0) res[1][26]=a3;
  if (res[1]!=0) res[1][27]=a3;
  if (res[1]!=0) res[1][28]=a3;
  if (res[1]!=0) res[1][29]=a3;
  if (res[1]!=0) res[1][30]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int model_2021_02_24_09504410_cost_y_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int model_2021_02_24_09504410_cost_y_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int model_2021_02_24_09504410_cost_y_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_2021_02_24_09504410_cost_y_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int model_2021_02_24_09504410_cost_y_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_2021_02_24_09504410_cost_y_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void model_2021_02_24_09504410_cost_y_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void model_2021_02_24_09504410_cost_y_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int model_2021_02_24_09504410_cost_y_fun_jac_ut_xt_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int model_2021_02_24_09504410_cost_y_fun_jac_ut_xt_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real model_2021_02_24_09504410_cost_y_fun_jac_ut_xt_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_2021_02_24_09504410_cost_y_fun_jac_ut_xt_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_2021_02_24_09504410_cost_y_fun_jac_ut_xt_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_2021_02_24_09504410_cost_y_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_2021_02_24_09504410_cost_y_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int model_2021_02_24_09504410_cost_y_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
